// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DATA.Dbcontext;

#nullable disable

namespace _1.DATA.Migrations
{
    [DbContext(typeof(SVDbcontext))]
    partial class SVDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1.DATA.Model.SinhVien", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("DiemTB")
                        .HasColumnType("real");

                    b.Property<string>("Eamil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("tuoi")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
